util.AddNetworkString('sv_network_rpc_callback')
util.AddNetworkString('cl_network_rpc_callback')
util.AddNetworkString('sv_network_rpc_success')
util.AddNetworkString('cl_network_rpc_success')
util.AddNetworkString('sv_network_rpc_error')
util.AddNetworkString('cl_network_rpc_error')